ARG IMAGE_BUILDER_DEV=builder-dev:latest
FROM ${IMAGE_BUILDER_DEV} AS dev

FROM alpine:3.20

# # copy generated results from dev image
# COPY --from=dev /app /app
#
# # set the entrypoint
# ENTRYPOINT ["python", "app.py"]
